### ISSUE TITLE
API v2 deprecated

### ISSUE THREAD

**Issue by jfunction** [misterhat/ytsearch#1]
Hello - thanks for making this software. I was trying to play with it today and I got the following error:
```
{12:48}~ ➭ ytsearch test   
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: N
    at error (/usr/local/lib/node_modules/ytsearch/node_modules/sax/lib/sax.js:642:8)
    at strictFail (/usr/local/lib/node_modules/ytsearch/node_modules/sax/lib/sax.js:662:22)
    at Object.write (/usr/local/lib/node_modules/ytsearch/node_modules/sax/lib/sax.js:934:11)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/ytsearch/node_modules/xml2js/lib/xml2js.js:273:29)
    at Parser.parseString (/usr/local/lib/node_modules/ytsearch/node_modules/xml2js/lib/xml2js.js:6:61)
    at exports.parseString (/usr/local/lib/node_modules/ytsearch/node_modules/xml2js/lib/xml2js.js:296:19)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ytsearch/node_modules/youtube-search/index.js:45:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
```

So I dug a little deeper and found that `youtube-search/index.js` is querying `gdata.youtube.com/feeds/api/videos?q=test&start-index=1&max-results=1` and getting "No longer available" as a result. I guess this is because [APIv2 is deprecated](https://developers.google.com/youtube/2.0/developers_guide_protocol_video_feeds).

Am I correct? If so, are there plans to move to v3 or any other current work arounds?

**Comment by misterhat** [comment]
No, I'm not interested in supporting YouTube or their crappy authenticated APIs. I will probably make a module for vid.me soon instead. If anybody else wants this package name for a replacement I'd be happy to give it to them.
